# -*- coding: utf-8 -*-
"""Coffee Shop Daily Revenue Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12M1ZSkI64Rgg0p3BGMnBWWNJoA4cdRUb
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/coffee_shop_revenue(in).csv')
df.head()

df.isnull().sum()

df.info()

df.describe()

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

total_revenue = df['Daily_Revenue'].sum()
total_revenue

print(df.corr()['Daily_Revenue'].sort_values(ascending=False))

plt.subplot(2, 3, 1)
sns.histplot(df['Number_of_Customers_Per_Day'], bins=30, kde=True, color='blue')
plt.title('Distribution of Number of Customers')

# 2. Daily Revenue Trend
plt.subplot(2, 3, 2)
plt.plot(df['Daily_Revenue'], color='orange')
plt.title('Daily Revenue Trend')
plt.xlabel('Day')
plt.ylabel('Revenue')